version: "3.1"

networks:
  lvl1-partners:

services:

  webserver:
    image: nginx:alpine
    container_name: lvl1-partners-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ../packages:/packages
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8180:80"
    networks:
      - lvl1-partners

  php-fpm:
    build: phpdocker/php-fpm
    container_name: lvl1-partners-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ../packages:/packages
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - lvl1-partners

  mysql:
    image: mysql:8.0
    container_name: lvl1-partners-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=lvl1-partners
      - MYSQL_USER=lvl1-partners
      - MYSQL_PASSWORD=secret
    ports:
      - "8086:3306"
    networks:
      - lvl1-partners

  adminer:
    image: adminer
    container_name: lvl1-partners-adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - lvl1-partners
